(setq *start-symbols* '("NP" "VP" "S"))
(setq *ltig* '(
(("S" ("NP" (:subst . "NP")) ("VP" ("V" "SIEHT"))) 1 . 1)
(("NP" ("DET" "DER") ("N" "MANN")) 1 . 0.25)
(("NP" ("N" "MANN")) 1 . 0.25)
(("NP" ("NE" "MANN")) 1 . 0.25)
(("NP" ("ADJ" "KLEINE") (:lfoot . "NP")) 1 . 0.25)
(("NP" ("ADJ" "TIEFE") ("XP" (:lfoot . "NP"))) 1 . 0.25)
(("VP" (:rfoot . "VP") ("ADV" "SCHNELL")) 1 . 0.5)
(("VP" (:rfoot . "VP") ("ADV" "DOOF")) 1 . 0.5)
))
